#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

caddy_version="2.11.2"
caddy_hash="2513b289054386b76642a9e8bfc10d217df2b5361e4cdd0c72672b0eeab57ae737d57466eb70f1a44233cbcc697ecf21de88137ca45ef4b64f150a32b58f5f14"
if [ "$TARGETARCH" == "arm64" ]; then
  caddy_hash="630d1e096e3c9594fd2f4f7129356ee5d6c7e53d0ca1b9a0c7486612c6d752ff355c96738c7a28c60367a5f1da4b51afca731bb745fb0b97cda4c811214cdc48"
fi

task_working_dir
download "https://github.com/caddyserver/caddy/releases/download/v${caddy_version}/caddy_${caddy_version}_linux_${TARGETARCH}.tar.gz" "sha512" "$caddy_hash"
extract_download "caddy_${caddy_version}_linux_${TARGETARCH}.tar.gz"

install -D -m 755 "caddy" "$TEST_INSTALL_PREFIX/bin/caddy"

stamp
