#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

mailpit_version="1.29.0"
mailpit_hash="80cb7a6cc0287dca5426ab250e60a037f53bbec0f7e1dc1413ab03460172c9ac"
if [ "$TARGETARCH" == "arm64" ]; then
  mailpit_hash="1b3f4dc1e80942e0ab688077882e0403ce74b294c1f2b7a0f8ff5ce9f831c911"
fi

task_working_dir
download "https://github.com/axllent/mailpit/releases/download/v${mailpit_version}/mailpit-linux-${TARGETARCH}.tar.gz" "sha256" "$mailpit_hash"
extract_download "mailpit-linux-${TARGETARCH}.tar.gz"

install -D -m 755 "mailpit" "$TEST_INSTALL_PREFIX/bin/mailpit"

stamp
