#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.161.1"
hugo_hash="9b82cf3211b2321f189a005dd157e6f4bd5c65f2bf5e9eefd2f5e0803c12103c"
if [ "$TARGETARCH" == "arm64" ]; then
  hugo_hash="e05382fbe2b2b9e51dfd01fbb6cd439d84c83a1862ac92000b25fbf2c06f699c"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
